//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinballServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerTBL
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public System.DateTime registerDate { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public string username { get; set; }
    }
}
